name = "AlcyonRegistry"
uuid = "b5a61a81-c931-459e-bfb1-25ca34650522"
repo = "https://github.com/alcyon-lab/AlcyonRegistry.git"
description = "Julia package registry that contains all the Alcyon packages."

[packages]
8e141ef3-93ad-4b93-8838-3aa69831e2fc = { name = "AlcyonValue", path = "A/AlcyonValue" }
a33b2169-df44-41c1-bcb8-32c383ca81e5 = { name = "Values", path = "V/Values" }
