name = "AlcyonRegistry"
uuid = "b5a61a81-c931-459e-bfb1-25ca34650522"
repo = "https://github.com/alcyon-lab/AlcyonRegistry.git"
description = "Julia package registry that contains all the Alcyon packages."

[packages]
26e1cdcf-0d11-452a-80c0-82a5afc2740a = { name = "Cones", path = "C/Cones" }
40aba029-825d-41bd-a97e-db86442ba04f = { name = "Polynomials", path = "P/Polynomials" }
86cf9b30-10dd-4360-aae2-6440cfec5ab7 = { name = "Optimization", path = "O/Optimization" }
a33b2169-df44-41c1-bcb8-32c383ca81e5 = { name = "Values", path = "V/Values" }
eaf9ee71-49fa-48f8-9df8-a09e5cbbfabf = { name = "PolyhedralOmega", path = "P/PolyhedralOmega" }
